export const colorMapping: { [key: string]: string } = {
    Z: "#cedcf4",
    Y: "#e0eba5",
    X: "#ffebb2",
    W: "#e0d9fa",
    V: "#efefef",
    U: "#ffebb2",
    T: "#cedcf4",
    S: "#e0eba5",
    R: "#ffebb2",
    Q: "#e0d9fa",
    P: "#efefef",
    O: "#cedcf4",
    N: "#e0eba5",
    M: "#ffebb2",
    L: "#e0d9fa",
    K: "#efefef",
    J: "#cedcf4",
    I: "#e0eba5",
    H: "#ffebb2",
    G: "#e0d9fa",
    F: "#efefef",
    E: "#cedcf4",
    D: "#e0eba5",
    C: "#ffebb2",
    B: "#e0d9fa",
    A: "#efefef",
  };

export const intrestOptions = [
    { value: 'AI', label: 'AI' },
    { value: 'Arts & Entertainment', label: 'Arts & Entertainment' },
    { value: 'B2B', label: 'B2B' },
    { value: 'B2C', label: 'B2C' },
    { value: 'Consulting', label: 'Consulting' },
    { value: 'Content Creation', label: 'Content Creation' },
    { value: 'Data', label: 'Data' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'Finance', label: 'Finance' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Banking', label: 'Banking' },
    { value: 'IoT', label: 'IoT' },
    { value: 'Leadership', label: 'Leadership' },
    { value: 'Logistics', label: 'Logistics' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Networking', label: 'Networking' },
    { value: 'Operations', label: 'Operations' },
    { value: 'PR', label: 'PR' },
    { value: 'Product Development', label: 'Product Development' },
    { value: 'Remote work', label: 'Remote work' },
    { value: 'Working in coffee shops', label: 'Working in coffee shops' },
    { value: 'Sales', label: 'Sales' },
    { value: 'SaaS', label: 'SaaS' },
    { value: 'Social Media', label: 'Social Media' },
    { value: 'Software Development', label: 'Software Development' },
    { value: 'Startups', label: 'Startups' },
    { value: 'Tech', label: 'Tech' },
    { value: 'Travel', label: 'Travel' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Interest', label: 'Interest'},
    { value: 'Government', label: 'Government'},
    { value: 'Freelancer', label: 'Freelancer'}
];