name: "cloudfront-update-dev"

on: workflow_dispatch

jobs:
  login-and-force-cloudfront-update:
    runs-on: ubuntu-latest
    steps:
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
